project_id = "qvirgcrbnwcyhbqdazjy"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_email = true

[database]
major_version = 15

[storage]
enabled = true

[edge_functions]
enabled = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.payment-reminders]
verify_jwt = false

[functions.create-payment-plan]
verify_jwt = true

[functions.handle-payment-success]
verify_jwt = true

[functions.process-installment-payment]
verify_jwt = false